<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa_Dato\Capa_Dato.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Users\Administrador\Escritorio\Orden de Compra\Capa_Negocio\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Users\Administrador\Escritorio\Orden de Compra\Capa_Negocio\.editorconfig" />
  </ItemGroup>

</Project>
