CREATE DATABASE PRUEBA_CONTABILIDAD;
GO

USE PRUEBA_CONTABILIDAD;
GO

CREATE TABLE ESTADO(
 IDESTADO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200),
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE()
);
GO

ALTER TABLE ESTADO
ADD MODULO VARCHAR(50) NULL;


CREATE TABLE ROL (
    IDROL INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(200),
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    IDESTADO INT,
    CONSTRAINT FK_ROL_ESTADO FOREIGN KEY (IDESTADO)
        REFERENCES ESTADO(IDESTADO)
);
GO

CREATE TABLE USUARIO (
    IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
    IDROL INT NOT NULL,
	NOMBRES VARCHAR (100),
    APELLIDOS VARCHAR (100),
    IDESTADO INT NOT NULL DEFAULT 1,
    NOMBREUSUARIO VARCHAR(100) NOT NULL UNIQUE,
    CORREO VARCHAR(150) NOT NULL UNIQUE,
    CLAVE VARCHAR(256) NOT NULL,
	REESTABLECER BIT DEFAULT 1,
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_USUARIO_ESTADO FOREIGN KEY (IDESTADO)
        REFERENCES ESTADO(IDESTADO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (IDROL)
        REFERENCES ROL(IDROL)
);
GO


-- Tabla MODULO
CREATE TABLE MODULO (
    IDMODULO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBREMODULO VARCHAR(100) NOT NULL,
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
);
GO

-- Tabla SUBMENU
CREATE TABLE SUBMENU (
    IDSUBMENU INT IDENTITY(1,1) PRIMARY KEY,
    IDMODULO INT NOT NULL,
    NOMBRESUBMENU VARCHAR(100) NOT NULL,
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_SUBMENU_MODULO FOREIGN KEY (IDMODULO)
        REFERENCES MODULO(IDMODULO),
);
GO

-- Tabla ACCION
CREATE TABLE ACCION (
    IDACCION INT IDENTITY(1,1) PRIMARY KEY,
    IDSUBMENU INT NOT NULL,
    NOMBREACCION VARCHAR(100) NOT NULL,
    FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_ACCION_SUBMENU FOREIGN KEY (IDSUBMENU)
        REFERENCES SUBMENU(IDSUBMENU),
);
GO

CREATE TABLE PERMISO (
    IDPERMISO INT IDENTITY(1,1) PRIMARY KEY,
    IDROL INT NOT NULL,
	IDMODULO INT NULL,
    IDSUBMENU INT NULL,
    IDACCION INT NULL,
    FECHAASIGNACION DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_PERMISO_MODULO FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    CONSTRAINT FK_PERMISO_SUBMENU FOREIGN KEY (IDSUBMENU) REFERENCES SUBMENU(IDSUBMENU),
    CONSTRAINT FK_PERMISO_ACCION FOREIGN KEY (IDACCION) REFERENCES ACCION(IDACCION),
    CONSTRAINT FK_PERMISO_ROL FOREIGN KEY (IDROL) REFERENCES ROL(IDROL)
);
GO


CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR     INT IDENTITY(1,1) PRIMARY KEY,
	HQID             INT           NOT NULL,
    PAIS             VARCHAR(30)  NOT NULL,
    FECHA_ACTUALIZACION DATETIME   NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(100)  NOT NULL,
    NOMBRE_CONTACTO  VARCHAR(30)  NOT NULL,
    CIUDAD           VARCHAR(30)  NOT NULL,
    DIRECCION        VARCHAR(MAX)  NOT NULL, -- Address1 + Address2
    CORREO           VARCHAR(255) NOT NULL,
    SITIO_WEB        VARCHAR(255) NOT NULL,
    RUC              VARCHAR(30)  NOT NULL,
    NUMERO_TELEFONO  VARCHAR(100)  NOT NULL,
    FAX              VARCHAR(100)  NOT NULL,
    TERMINOS         VARCHAR(50)  NOT NULL
);
GO

ALTER TABLE PROVEEDORES
ADD CONSTRAINT UQ_PROVEEDORES_HQID UNIQUE(HQID);

CREATE TABLE ESTADO_ORDEN
(
    IDESTADO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
	FECHAREGISTRO DATETIME NOT NULL DEFAULT GETDATE()

);
GO
-- Insertar los estados iniciales
INSERT INTO ESTADO_ORDEN (NOMBRE)
VALUES ('PENDIENTE'), ('PAGADO');

CREATE TABLE ORDENES_COMPRA
(
    IDORDEN INT IDENTITY(1,1) PRIMARY KEY,
    IDORDENCOMPRA INT NOT NULL,           -- ID real de FSCDBd
    HQID INT NOT NULL,                     -- FK hacia PROVEEDORES
    NUMERO_ORDEN NVARCHAR(50),
    STATUS_ORDEN NVARCHAR(50) ,   -- CERRADO
    FACTURA NVARCHAR(100) ,
	COMENTARIO   NVARCHAR(100) ,
    FECHA_CREACION DATETIME NOT NULL,
    TOTAL DECIMAL(18,2) NOT NULL,
    IDESTADO INT NOT NULL DEFAULT 1,      -- 1 = PENDIENTE
    IDUSUARIOPAGO INT NULL,               -- FK hacia USUARIO
    FECHA_PAGO DATETIME NULL,
    CONSTRAINT UQ_ORDEN_UNICA UNIQUE(IDORDENCOMPRA),
    CONSTRAINT FK_ESTADO_ORDEN FOREIGN KEY(IDESTADO) REFERENCES ESTADO_ORDEN(IDESTADO),
    CONSTRAINT FK_USUARIO_PAGO FOREIGN KEY(IDUSUARIOPAGO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_PROVEEDOR_HQID FOREIGN KEY(HQID) REFERENCES PROVEEDORES(HQID)
);
GO

CREATE TABLE VENCIDOS
(
    IDVENCIDO INT IDENTITY(1,1) PRIMARY KEY,
    IDORDENVENCIDO INT NOT NULL,           -- ID real de FSCDBd
    HQID INT NOT NULL,                     -- FK hacia PROVEEDORES
    NUMERO_ORDEN NVARCHAR(50),
    STATUS_ORDEN NVARCHAR(50) ,   -- CERRADO
	CONCEPTO   NVARCHAR(150) ,
    FECHA_CREACION DATETIME NOT NULL,
	USUARIO NVARCHAR(50) NOT NULL,
    TOTAL DECIMAL(18,2) NOT NULL,
    IDESTADO INT NOT NULL DEFAULT 5,      -- 5 = PENDIENTE
    IDUSUARIOPAGO INT NULL,               -- FK hacia USUARIO
    FECHA_PAGO DATETIME NULL,
    CONSTRAINT UQ_ORDENVEN_UNICA UNIQUE(IDORDENVENCIDO),
    CONSTRAINT FK_ESTADO FOREIGN KEY(IDESTADO) REFERENCES ESTADO(IDESTADO),
    CONSTRAINT FK_USUARIO_VEN FOREIGN KEY(IDUSUARIOPAGO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_PROVEEDORVEN_HQID FOREIGN KEY(HQID) REFERENCES PROVEEDORES(HQID)
);
GO


CREATE TABLE PAGO_VENCIDO
(
    ID_PAGO INT IDENTITY PRIMARY KEY,
    ID_VENCIDO INT NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(50) NOT NULL UNIQUE,
    FECHA_DOCUMENTO DATE,
    MONTO_TOTAL DECIMAL(18,2),
    OBSERVACION VARCHAR(300),
    IDESTADO INT NOT NULL, 
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_VENCIDO) REFERENCES VENCIDOS(IDVENCIDO),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
GO

CREATE TABLE DETALLE_PAGO_VENCIDO
(
    ID_DETALLE_PAGO INT IDENTITY PRIMARY KEY,
    ID_PAGO INT NOT NULL,
    MONTO_PAGADO DECIMAL(18,2) NOT NULL,
    ID_TIPO_DOC INT NOT NULL,
    COMPROBANTE VARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_PAGO) REFERENCES PAGO_VENCIDO(ID_PAGO),
    FOREIGN KEY (ID_TIPO_DOC) REFERENCES TIPO_DOCUMENTO_PAGO(ID_TIPO_DOC)
)
GO

