-- Obtener acuerdos
CREATE OR ALTER PROCEDURE SP_OBTENER_ACUERDO_REBATE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        A.ID_ACUERDO,
        A.NUMERO_ACUERDO,
        A.NOMBRE_ACUERDO,
        A.VALOR_CRITERIO,
        A.GANANCIA,
        A.FECHA_INICIO,
        A.FECHA_FIN,
        A.FECHA_REGISTRO,
        A.USUARIO_CREACION,
        A.DOCUMENTO,
        A.COMENTARIO,

        P.ID_PROVEEDOR,
        P.NOMBRE_PROVEEDOR,

        MO.ID_MODALIDAD_OP,
        MO.NOMBRE AS MODALIDAD_OP,

        TR.ID_TIPO_REBATE,
        TR.NOMBRE AS TIPO_REBATE,

        CR.ID_CRITERIO,
        CR.NOMBRE AS CRITERIO,

        PA.ID_PAIS,
        PA.NOMBRE AS PAIS,

        M.ID_MONEDA,
        M.NOMBRE AS MONEDA,

        E.IDESTADO,
        E.NOMBRE AS ESTADO

    FROM ACUERDO_REBATE A
    INNER JOIN PROVEEDORES P ON P.ID_PROVEEDOR = A.ID_PROVEEDOR
    INNER JOIN MODALIDAD_OPERACION MO ON MO.ID_MODALIDAD_OP = A.ID_MODALIDAD_OP
    INNER JOIN TIPO_REBATE TR ON TR.ID_TIPO_REBATE = A.ID_TIPO_REBATE
    INNER JOIN CRITERIO_REBATE CR ON CR.ID_CRITERIO = A.ID_CRITERIO
    INNER JOIN PAIS PA ON PA.ID_PAIS = A.ID_PAIS
    INNER JOIN MONEDA M ON M.ID_MONEDA = A.ID_MONEDA
    INNER JOIN ESTADO E ON E.IDESTADO = A.IDESTADO
    ORDER BY A.ID_ACUERDO ASC;  -- puedes cambiar a FECHA_REGISTRO si prefieres
END
GO


CREATE SEQUENCE SEQ_NUMERO_ACUERDO
AS BIGINT
START WITH 1
INCREMENT BY 1;
GO


-- Crear acuerdo
CREATE OR ALTER PROCEDURE SP_CREAR_ACUERDO_REBATE
(
    @NOMBRE_ACUERDO VARCHAR(200),
    @ID_PROVEEDOR INT,
    @ID_MODALIDAD_OP INT,
    @ID_TIPO_REBATE INT,
    @ID_CRITERIO INT,
    @VALOR_CRITERIO DECIMAL(18,2),
    @GANANCIA DECIMAL(18,2),
    @ID_PAIS INT,
    @ID_MONEDA INT,
    @FECHA_INICIO DATE,
    @FECHA_FIN DATE,
    @COMENTARIO VARCHAR(MAX),
    @USUARIO_CREACION VARCHAR(100),
    @DOCUMENTO VARCHAR(255) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO ACUERDO_REBATE
    (
        NUMERO_ACUERDO,
        NOMBRE_ACUERDO,
        ID_PROVEEDOR,
        ID_MODALIDAD_OP,
        ID_TIPO_REBATE,
        ID_CRITERIO,
        VALOR_CRITERIO,
        GANANCIA,
        ID_PAIS,
        ID_MONEDA,
        FECHA_INICIO,
        FECHA_FIN,
        IDESTADO,
        COMENTARIO,
        USUARIO_CREACION,
        DOCUMENTO
    )
    VALUES
    (
        'ACR-' + FORMAT(NEXT VALUE FOR SEQ_NUMERO_ACUERDO, '0000000'),
        @NOMBRE_ACUERDO,
        @ID_PROVEEDOR,
        @ID_MODALIDAD_OP,
        @ID_TIPO_REBATE,
        @ID_CRITERIO,
        @VALOR_CRITERIO,
        @GANANCIA,
        @ID_PAIS,
        @ID_MONEDA,
        @FECHA_INICIO,
        @FECHA_FIN,
        DEFAULT,
        @COMENTARIO,
        @USUARIO_CREACION,
        @DOCUMENTO
    );
END
GO


-- Editar acuerdo
CREATE OR ALTER PROCEDURE SP_EDITAR_ACUERDO_REBATE
(
    @ID_ACUERDO INT,
    @NOMBRE_ACUERDO VARCHAR(200),
    @ID_PROVEEDOR INT,
    @ID_MODALIDAD_OP INT,
    @ID_TIPO_REBATE INT,
    @ID_CRITERIO INT,
    @VALOR_CRITERIO DECIMAL(18,2),
    @GANANCIA DECIMAL(18,2),
    @ID_PAIS INT,
    @ID_MONEDA INT,
    @FECHA_INICIO DATE,
    @FECHA_FIN DATE,
    @COMENTARIO VARCHAR(MAX),
    @DOCUMENTO VARCHAR(255) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE ACUERDO_REBATE
    SET
        NOMBRE_ACUERDO = @NOMBRE_ACUERDO,
        ID_PROVEEDOR = @ID_PROVEEDOR,
        ID_MODALIDAD_OP = @ID_MODALIDAD_OP,
        ID_TIPO_REBATE = @ID_TIPO_REBATE,
        ID_CRITERIO = @ID_CRITERIO,
        VALOR_CRITERIO = @VALOR_CRITERIO,
        GANANCIA = @GANANCIA,
        ID_PAIS = @ID_PAIS,
        ID_MONEDA = @ID_MONEDA,
        FECHA_INICIO = @FECHA_INICIO,
        FECHA_FIN = @FECHA_FIN,
        COMENTARIO = @COMENTARIO,
        DOCUMENTO = @DOCUMENTO
    WHERE ID_ACUERDO = @ID_ACUERDO;
END
GO


----EJECUCION REBATE
 CREATE OR ALTER PROCEDURE SP_OBTENER_EJECUCIONES
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ER.ID_EJECUCION,
        ER.NUMERO_DOCUMENTO_SOPORTE,
        ER.MONTO_CALCULADO,
        ER.CUMPLE_CONDICION,
        ER.MONTO_REBATE,
        ER.ARCHIVO_SOPORTE,
        ER.FECHA_REGISTRO,
		ER.USUARIO_REGISTRO,


        -- Acuerdo
        A.ID_ACUERDO,
        A.NUMERO_ACUERDO,
        A.NOMBRE_ACUERDO,
        A.VALOR_CRITERIO,
        C.NOMBRE AS CRITERIO,
        C.OPERADOR,
        A.GANANCIA,

        -- Proveedor
        P.ID_PROVEEDOR,
        P.NOMBRE_PROVEEDOR,

        -- Estado
        E.IDESTADO,
        E.NOMBRE AS ESTADO
    FROM EJECUCION_REBATE ER
    INNER JOIN ACUERDO_REBATE A ON A.ID_ACUERDO = ER.ID_ACUERDO
    INNER JOIN CRITERIO_REBATE C ON C.ID_CRITERIO = A.ID_CRITERIO
    INNER JOIN PROVEEDORES P ON P.ID_PROVEEDOR = A.ID_PROVEEDOR
    INNER JOIN ESTADO E ON E.IDESTADO = ER.IDESTADO
    ORDER BY ER.FECHA_REGISTRO DESC;
END
GO

--falta para abajo
CREATE SEQUENCE SEQ_NUMERO_EJECUCION_REBATE
AS BIGINT
START WITH 1
INCREMENT BY 1;
GO

-- ===========================================
-- CREAR EJECUCION REBATE
-- ===========================================
CREATE OR ALTER PROCEDURE SP_CREAR_EJECUCION_REBATE
(
    @ID_ACUERDO INT,
    @MONTO_CALCULADO DECIMAL(18,2),
    @ARCHIVO_SOPORTE VARCHAR(300),
    @USUARIO_REGISTRO VARCHAR(100),   
    @IDESTADO INT = 1
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE 
        @VALOR_CRITERIO DECIMAL(18,2),
        @GANANCIA DECIMAL(18,2),
        @OPERADOR VARCHAR(10),
        @CUMPLE_CONDICION BIT = 0,
        @MONTO_REBATE DECIMAL(18,2) = 0,
        @IDESTADO_FINAL INT;

    -- OBTENER DATOS DEL ACUERDO Y CRITERIO
    SELECT
        @VALOR_CRITERIO = A.VALOR_CRITERIO,
        @GANANCIA = A.GANANCIA,
        @OPERADOR = C.OPERADOR
    FROM ACUERDO_REBATE A
    INNER JOIN CRITERIO_REBATE C ON C.ID_CRITERIO = A.ID_CRITERIO
    WHERE A.ID_ACUERDO = @ID_ACUERDO;

    IF @OPERADOR IS NULL
    BEGIN
        RAISERROR('No se encontró el acuerdo o el criterio.',16,1);
        RETURN;
    END

    -- CALCULO DEL REBATE
    IF @OPERADOR = '>'
    BEGIN
        IF @MONTO_CALCULADO > @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @GANANCIA * FLOOR(@MONTO_CALCULADO / @VALOR_CRITERIO);
        END
    END
    ELSE IF @OPERADOR = '>='
    BEGIN
        IF @MONTO_CALCULADO >= @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @GANANCIA * FLOOR(@MONTO_CALCULADO / @VALOR_CRITERIO);
        END
    END
    ELSE IF @OPERADOR = '%'
    BEGIN
        IF @MONTO_CALCULADO >= @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @MONTO_CALCULADO * (@GANANCIA / 100.0);
        END
    END
    ELSE
    BEGIN
        RAISERROR('Operador de criterio no soportado.',16,1);
        RETURN;
    END

    -- DETERMINAR ESTADO FINAL
    SET @IDESTADO_FINAL = CASE 
                              WHEN @CUMPLE_CONDICION = 0 THEN 4
                              WHEN EXISTS (SELECT 1 FROM ESTADO WHERE IDESTADO = @IDESTADO) THEN @IDESTADO
                              ELSE 1  -- Por defecto ACTIVO
                           END;

    -- INSERTAR EJECUCION
    INSERT INTO EJECUCION_REBATE
    (
        ID_ACUERDO,
        NUMERO_DOCUMENTO_SOPORTE,
        MONTO_CALCULADO,
        CUMPLE_CONDICION,
        MONTO_REBATE,
        ARCHIVO_SOPORTE,
        IDESTADO,
		USUARIO_REGISTRO    
    )
    VALUES
    (
        @ID_ACUERDO,
        'REB-' + FORMAT(NEXT VALUE FOR SEQ_NUMERO_EJECUCION_REBATE,'000000'),
        @MONTO_CALCULADO,
        @CUMPLE_CONDICION,
        @MONTO_REBATE,
        @ARCHIVO_SOPORTE,
        @IDESTADO_FINAL,
		 @USUARIO_REGISTRO  
    );
END
GO

-- ===========================================
-- EDITAR EJECUCION REBATE
-- ===========================================
CREATE OR ALTER PROCEDURE SP_EDITAR_EJECUCION_REBATE
(
    @ID_EJECUCION INT,
    @MONTO_CALCULADO DECIMAL(18,2) = NULL,
    @ARCHIVO_SOPORTE VARCHAR(300) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE
        @ID_ACUERDO INT,
        @VALOR_CRITERIO DECIMAL(18,2),
        @GANANCIA DECIMAL(18,2),
        @OPERADOR VARCHAR(10),
        @MONTO_ANT DECIMAL(18,2),
        @ARCHIVO_ANT VARCHAR(300),
        @CUMPLE_CONDICION BIT = 0,
        @MONTO_REBATE DECIMAL(18,2) = 0,
        @IDESTADO_FINAL INT,
        @MONTO_CALC DECIMAL(18,2);

    -- DATOS DE LA EJECUCIÓN
    SELECT 
        @ID_ACUERDO = ID_ACUERDO,
        @MONTO_ANT = MONTO_CALCULADO,
        @ARCHIVO_ANT = ARCHIVO_SOPORTE
    FROM EJECUCION_REBATE
    WHERE ID_EJECUCION = @ID_EJECUCION;

    IF @ID_ACUERDO IS NULL
    BEGIN
        RAISERROR('No se encontró la ejecución.',16,1);
        RETURN;
    END

    -- DATOS DEL ACUERDO Y CRITERIO
    SELECT
        @VALOR_CRITERIO = A.VALOR_CRITERIO,
        @GANANCIA = A.GANANCIA,
        @OPERADOR = C.OPERADOR
    FROM ACUERDO_REBATE A
    INNER JOIN CRITERIO_REBATE C ON C.ID_CRITERIO = A.ID_CRITERIO
    WHERE A.ID_ACUERDO = @ID_ACUERDO;

    IF @OPERADOR IS NULL
    BEGIN
        RAISERROR('No se encontró el criterio del acuerdo.',16,1);
        RETURN;
    END

    -- MONTO A EVALUAR
    SET @MONTO_CALC = ISNULL(@MONTO_CALCULADO, @MONTO_ANT);

    -- CALCULO DEL REBATE (MISMA LÓGICA QUE CREAR)
    IF @OPERADOR = '>'
    BEGIN
        IF @MONTO_CALC > @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @GANANCIA * FLOOR(@MONTO_CALC / @VALOR_CRITERIO);
        END
    END
    ELSE IF @OPERADOR = '>='
    BEGIN
        IF @MONTO_CALC >= @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @GANANCIA * FLOOR(@MONTO_CALC / @VALOR_CRITERIO);
        END
    END
    ELSE IF @OPERADOR = '%'
    BEGIN
        IF @MONTO_CALC >= @VALOR_CRITERIO
        BEGIN
            SET @CUMPLE_CONDICION = 1;
            SET @MONTO_REBATE = @MONTO_CALC * (@GANANCIA / 100.0);
        END
    END

    -- 🔥 ESTADO FINAL (IGUAL QUE CREAR)
    SET @IDESTADO_FINAL = CASE 
                              WHEN @CUMPLE_CONDICION = 0 THEN 4
                              ELSE 1
                          END;

    -- ACTUALIZAR EJECUCIÓN
    UPDATE EJECUCION_REBATE
    SET
        MONTO_CALCULADO = @MONTO_CALC,
        CUMPLE_CONDICION = @CUMPLE_CONDICION,
        MONTO_REBATE = @MONTO_REBATE,
        ARCHIVO_SOPORTE = ISNULL(@ARCHIVO_SOPORTE, @ARCHIVO_ANT),
        IDESTADO = @IDESTADO_FINAL
    WHERE ID_EJECUCION = @ID_EJECUCION;
END
GO



------pago rebate
CREATE TYPE T_DETALLE_PAGO_REBATE AS TABLE
(
    ID_EJECUCION INT,
    MONTO_PAGADO DECIMAL(18,2),
    ID_TIPO_DOCUMENTO INT,
    COMPROBANTE VARCHAR(MAX)
);
GO

DROP TYPE IF EXISTS T_DETALLE_PAGO_REBATE;
GO

CREATE TYPE T_DETALLE_PAGO_REBATE AS TABLE
(
    ID_EJECUCION INT,
    MONTO_PAGADO DECIMAL(18,2),
    ID_TIPO_DOCUMENTO INT,
    COMPROBANTE VARCHAR(MAX),
    USUARIO_PAGO VARCHAR(100)   -- nueva columna
);
GO


CREATE OR ALTER PROCEDURE SP_REGISTRAR_PAGO_REBATE
(
    @ID_ACUERDO INT,
    @FECHA_DOCUMENTO DATE,
    @MONTO_TOTAL DECIMAL(18,2),
    @OBSERVACION VARCHAR(300),
    @DETALLE T_DETALLE_PAGO_REBATE READONLY,
    @ID_PAGO_REBATE INT OUTPUT,
    @NUMERO_DOCUMENTO_OUT VARCHAR(20) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @CORRELATIVO INT;
    DECLARE @LARGO INT;

    BEGIN TRY
        BEGIN TRAN;

        /* ===============================
           GENERAR NÚMERO DE DOCUMENTO
           =============================== */
        SELECT @CORRELATIVO = ISNULL(MAX(CAST(NUMERO_DOCUMENTO AS INT)), 0) + 1
        FROM PAGO_REBATE;

        SET @LARGO = CASE 
                        WHEN LEN(@CORRELATIVO) < 4 THEN 4 
                        ELSE LEN(@CORRELATIVO) 
                     END;

        SET @NUMERO_DOCUMENTO_OUT =
            RIGHT(REPLICATE('0', @LARGO) + CAST(@CORRELATIVO AS VARCHAR), @LARGO);

        /* ===============================
           INSERT CABECERA DE PAGO
           =============================== */
        INSERT INTO PAGO_REBATE
        (
            ID_ACUERDO,
            NUMERO_DOCUMENTO,
            MONTO_TOTAL,
            OBSERVACION,
            IDESTADO,
            FECHA_REGISTRO
        )
        VALUES
        (
            @ID_ACUERDO,
            @NUMERO_DOCUMENTO_OUT,
            @MONTO_TOTAL,
            @OBSERVACION,
            6,             -- PAGADO
            GETDATE()
        );

        SET @ID_PAGO_REBATE = SCOPE_IDENTITY();

        /* ===============================
           INSERT DETALLE DE PAGO
           =============================== */
        INSERT INTO DETALLE_PAGO_REBATE
        (
            ID_PAGO_REBATE,
            ID_EJECUCION,
            MONTO_PAGADO,
            ID_TIPO_DOC,
            COMPROBANTE,
            USUARIO_PAGO
        )
        SELECT
            @ID_PAGO_REBATE,
            ID_EJECUCION,
            MONTO_PAGADO,
            ID_TIPO_DOCUMENTO,
            COMPROBANTE,
            USUARIO_PAGO
        FROM @DETALLE;

        /* ===============================
           ACTUALIZAR EJECUCIONES A PAGADAS
           =============================== */
        UPDATE ER
        SET ER.IDESTADO = 6   -- PAGADO
        FROM EJECUCION_REBATE ER
        INNER JOIN @DETALLE D 
            ON ER.ID_EJECUCION = D.ID_EJECUCION;

        COMMIT;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        THROW;
    END CATCH
END;
GO


CREATE OR ALTER PROCEDURE SP_LISTA_EJECUCIONES_REBATE_RESUMEN
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ER.ID_EJECUCION,
        ER.NUMERO_DOCUMENTO_SOPORTE,

        A.NUMERO_ACUERDO,
        A.NOMBRE_ACUERDO,

        P.NOMBRE_PROVEEDOR,
        TR.NOMBRE AS TIPO_REBATE,
        CR.NOMBRE AS CRITERIO,

        ER.MONTO_REBATE,

        ISNULL(SUM(DPR.MONTO_PAGADO), 0) AS MONTO_PAGADO,
        ER.MONTO_REBATE - ISNULL(SUM(DPR.MONTO_PAGADO), 0) AS SALDO_PENDIENTE,

        ER.IDESTADO AS ID_ESTADO_EJECUCION,
        E.NOMBRE AS ESTADO_EJECUCION,

        ER.FECHA_REGISTRO
    FROM EJECUCION_REBATE ER
        INNER JOIN ACUERDO_REBATE A ON A.ID_ACUERDO = ER.ID_ACUERDO
        INNER JOIN PROVEEDORES P ON P.ID_PROVEEDOR = A.ID_PROVEEDOR
        INNER JOIN TIPO_REBATE TR ON TR.ID_TIPO_REBATE = A.ID_TIPO_REBATE
        INNER JOIN CRITERIO_REBATE CR ON CR.ID_CRITERIO = A.ID_CRITERIO
        INNER JOIN ESTADO E ON E.IDESTADO = ER.IDESTADO
        LEFT JOIN DETALLE_PAGO_REBATE DPR ON DPR.ID_EJECUCION = ER.ID_EJECUCION
    WHERE
        ER.IDESTADO IN (1, 6)      -- 👈 SOLO PENDIENTE Y PAGADO
    GROUP BY
        ER.ID_EJECUCION,
        ER.NUMERO_DOCUMENTO_SOPORTE,
        A.NUMERO_ACUERDO,
        A.NOMBRE_ACUERDO,
        P.NOMBRE_PROVEEDOR,
        TR.NOMBRE,
        CR.NOMBRE,
        ER.MONTO_REBATE,
        ER.IDESTADO,
        E.NOMBRE,
        ER.FECHA_REGISTRO
    ORDER BY
        CASE 
            WHEN ER.IDESTADO = 1 THEN 1   -- PENDIENTE
            WHEN ER.IDESTADO = 6 THEN 2   -- PAGADO
        END,
        ER.FECHA_REGISTRO DESC;
END
GO

CREATE OR ALTER PROCEDURE SP_DETALLE_PAGO_EJECUCION_REBATE
    @ID_EJECUCION INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        DPR.ID_DETALLE_PAGO    AS IdDetallePago,
        PR.NUMERO_DOCUMENTO    AS DocumentoPago,
        DPR.MONTO_PAGADO       AS MontoPagado,
        TD.NOMBRE              AS TipoDocumento,
		DPR.USUARIO_PAGO       AS usuarioPago,
        DPR.FECHA_REGISTRO     AS FechaRegistro,
        DPR.COMPROBANTE        AS Comprobante
    FROM DETALLE_PAGO_REBATE DPR
    LEFT JOIN PAGO_REBATE PR 
        ON PR.ID_PAGO_REBATE = DPR.ID_PAGO_REBATE
    LEFT JOIN TIPO_DOCUMENTO_PAGO TD 
        ON TD.ID_TIPO_DOC = DPR.ID_TIPO_DOC
    WHERE DPR.ID_EJECUCION = @ID_EJECUCION
    ORDER BY DPR.FECHA_REGISTRO ASC;
END
GO


select * from DETALLE_PAGO_REBATE