USE ORDEN_COMPRA

--SP PARA TABLAS CATALOGOS 
--ESTADO 
CREATE OR ALTER PROCEDURE SP_OBTENER_ESTADO
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        IDESTADO,
        NOMBRE,
        DESCRIPCION,
        MODULO,
        FECHAREGISTRO
    FROM ESTADO
    ORDER BY NOMBRE;
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_ESTADO
    @NOMBRE VARCHAR(50),
    @DESCRIPCION VARCHAR(200) = NULL,
    @MODULO VARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Validar duplicado por nombre
    IF EXISTS (SELECT 1 FROM ESTADO WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('El estado ya existe.',16,1);
        RETURN;
    END

    INSERT INTO ESTADO (NOMBRE, DESCRIPCION, MODULO)
    VALUES (@NOMBRE, @DESCRIPCION, @MODULO);
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_ESTADO
    @IDESTADO INT,
    @NOMBRE VARCHAR(50),
    @DESCRIPCION VARCHAR(200) = NULL,
    @MODULO VARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Validar existencia
    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE IDESTADO = @IDESTADO)
    BEGIN
        RAISERROR('El estado no existe.',16,1);
        RETURN;
    END

    -- Validar duplicado en otro registro
    IF EXISTS (SELECT 1 FROM ESTADO WHERE NOMBRE = @NOMBRE AND IDESTADO <> @IDESTADO)
    BEGIN
        RAISERROR('Ya existe otro estado con el mismo nombre.',16,1);
        RETURN;
    END

    UPDATE ESTADO
    SET NOMBRE = @NOMBRE,
        DESCRIPCION = @DESCRIPCION,
        MODULO = @MODULO
    WHERE IDESTADO = @IDESTADO;
END
GO


--PAIS 
CREATE OR ALTER PROCEDURE SP_OBTENER_PAIS
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        P.ID_PAIS,
        P.NOMBRE,
        P.IDESTADO,
        E.NOMBRE AS ESTADO,
        P.FECHA_REGISTRO
    FROM PAIS P
    INNER JOIN ESTADO E ON P.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_PAIS
    @NOMBRE VARCHAR(100),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM PAIS WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('EL PAIS YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO PAIS (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_PAIS
    @ID_PAIS INT,
    @NOMBRE VARCHAR(100),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM PAIS WHERE ID_PAIS = @ID_PAIS)
    BEGIN
        RAISERROR('EL PAIS NO EXISTE.',16,1)
        RETURN
    END

    IF EXISTS (SELECT 1 FROM PAIS WHERE NOMBRE = @NOMBRE AND ID_PAIS <> @ID_PAIS)
    BEGIN
        RAISERROR('EL NOMBRE DEL PAIS YA EXISTE.',16,1)
        RETURN
    END

    UPDATE PAIS
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_PAIS = @ID_PAIS
END
GO


--MONEDA 
CREATE OR ALTER PROCEDURE SP_OBTENER_MONEDA
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        M.ID_MONEDA,
        M.NOMBRE,
        M.SIMBOLO,
        M.IDESTADO,
        E.NOMBRE AS ESTADO,
        M.FECHA_REGISTRO
    FROM MONEDA M
    INNER JOIN ESTADO E ON M.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_MONEDA
    @NOMBRE VARCHAR(50),
    @SIMBOLO VARCHAR(10),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM MONEDA WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('LA MONEDA YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO MONEDA (NOMBRE, SIMBOLO, IDESTADO)
    VALUES (@NOMBRE, @SIMBOLO, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_MONEDA
    @ID_MONEDA INT,
    @NOMBRE VARCHAR(50),
    @SIMBOLO VARCHAR(10),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM MONEDA WHERE ID_MONEDA = @ID_MONEDA)
    BEGIN
        RAISERROR('LA MONEDA NO EXISTE.',16,1)
        RETURN
    END

    UPDATE MONEDA
    SET NOMBRE = @NOMBRE,
        SIMBOLO = @SIMBOLO,
        IDESTADO = @IDESTADO
    WHERE ID_MONEDA = @ID_MONEDA
END
GO

---MODALIDAD OPERACION 
CREATE OR ALTER PROCEDURE SP_OBTENER_MODALIDAD_OPERACION
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        M.ID_MODALIDAD_OP,
        M.NOMBRE,
        M.IDESTADO,
        E.NOMBRE AS ESTADO,
        M.FECHA_REGISTRO
    FROM MODALIDAD_OPERACION M
    INNER JOIN ESTADO E ON M.IDESTADO = E.IDESTADO
END
GO


CREATE OR ALTER PROCEDURE SP_CREAR_MODALIDAD_OPERACION
    @NOMBRE VARCHAR(20),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('LA MODALIDAD YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO MODALIDAD_OPERACION (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO


CREATE OR ALTER PROCEDURE SP_EDITAR_MODALIDAD_OPERACION
    @ID_MODALIDAD_OP INT,
    @NOMBRE VARCHAR(20),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE ID_MODALIDAD_OP = @ID_MODALIDAD_OP)
    BEGIN
        RAISERROR('LA MODALIDAD NO EXISTE.',16,1)
        RETURN
    END

    IF EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE NOMBRE = @NOMBRE AND ID_MODALIDAD_OP <> @ID_MODALIDAD_OP)
    BEGIN
        RAISERROR('EL NOMBRE DE LA MODALIDAD YA EXISTE.',16,1)
        RETURN
    END

    UPDATE MODALIDAD_OPERACION
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_MODALIDAD_OP = @ID_MODALIDAD_OP
END
GO


--MODALIDAD
CREATE OR ALTER PROCEDURE SP_OBTENER_MODALIDAD
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        M.ID_MODALIDAD,
        M.NOMBRE,
        M.TIPO_INTERVALO,
        M.VALOR_INTERVALO,
        M.IDESTADO,
        E.NOMBRE AS ESTADO,
        M.FECHA_REGISTRO
    FROM MODALIDAD M
    INNER JOIN ESTADO E ON M.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_MODALIDAD
    @NOMBRE VARCHAR(50),
    @TIPO_INTERVALO VARCHAR(10),
    @VALOR_INTERVALO INT,
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM MODALIDAD WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('LA MODALIDAD YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO MODALIDAD (NOMBRE, TIPO_INTERVALO, VALOR_INTERVALO, IDESTADO)
    VALUES (@NOMBRE, @TIPO_INTERVALO, @VALOR_INTERVALO, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_MODALIDAD
    @ID_MODALIDAD INT,
    @NOMBRE VARCHAR(50),
    @TIPO_INTERVALO VARCHAR(10),
    @VALOR_INTERVALO INT,
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM MODALIDAD WHERE ID_MODALIDAD = @ID_MODALIDAD)
    BEGIN
        RAISERROR('LA MODALIDAD NO EXISTE.',16,1)
        RETURN
    END

    UPDATE MODALIDAD
    SET 
        NOMBRE = @NOMBRE,
        TIPO_INTERVALO = @TIPO_INTERVALO,
        VALOR_INTERVALO = @VALOR_INTERVALO,
        IDESTADO = @IDESTADO
    WHERE ID_MODALIDAD = @ID_MODALIDAD
END
GO

--TIPO PUBLICIDAD 
CREATE OR ALTER PROCEDURE SP_OBTENER_TIPO_PUBLICIDAD
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        T.ID_TIPO_PUBLICIDAD,
        T.NOMBRE,
        T.IDESTADO,
        E.NOMBRE AS ESTADO,
        T.FECHA_REGISTRO
    FROM TIPO_PUBLICIDAD T
    INNER JOIN ESTADO E ON T.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_TIPO_PUBLICIDAD
    @NOMBRE VARCHAR(50),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TIPO_PUBLICIDAD WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('EL TIPO DE PUBLICIDAD YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO TIPO_PUBLICIDAD (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_TIPO_PUBLICIDAD
    @ID_TIPO_PUBLICIDAD INT,
    @NOMBRE VARCHAR(50),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TIPO_PUBLICIDAD
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_TIPO_PUBLICIDAD = @ID_TIPO_PUBLICIDAD
END
GO

--TIPO REBATE 
CREATE OR ALTER PROCEDURE SP_OBTENER_TIPO_REBATE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        T.ID_TIPO_REBATE,
        T.NOMBRE,
        T.IDESTADO,
        E.NOMBRE AS ESTADO,
        T.FECHA_REGISTRO
    FROM TIPO_REBATE T
    INNER JOIN ESTADO E ON T.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_TIPO_REBATE
    @NOMBRE VARCHAR(100),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TIPO_REBATE WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('EL TIPO DE REBATE YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO TIPO_REBATE (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_TIPO_REBATE
    @ID_TIPO_REBATE INT,
    @NOMBRE VARCHAR(100),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TIPO_REBATE
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_TIPO_REBATE = @ID_TIPO_REBATE
END
GO

----- Tipo documento pago
CREATE OR ALTER PROCEDURE SP_OBTENER_TIPO_DOC
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        T.ID_TIPO_DOC,
        T.NOMBRE,
        T.IDESTADO,
        E.NOMBRE AS ESTADO,
        T.FECHA_REGISTRO
    FROM TIPO_DOCUMENTO_PAGO T
    INNER JOIN ESTADO E ON T.IDESTADO = E.IDESTADO
END
GO

CREATE OR ALTER PROCEDURE SP_CREAR_TIPO_DOC
    @NOMBRE VARCHAR(50),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TIPO_DOCUMENTO_PAGO WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('EL TIPO DE DOCUMENTO YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO TIPO_DOCUMENTO_PAGO (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO

CREATE OR ALTER PROCEDURE SP_EDITAR_TIPO_DOC
    @ID_TIPO_DOC INT,
    @NOMBRE VARCHAR(50),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM TIPO_DOCUMENTO_PAGO WHERE ID_TIPO_DOC = @ID_TIPO_DOC)
    BEGIN
        RAISERROR('EL TIPO DE DOCUMENTO NO EXISTE.',16,1)
        RETURN
    END

    UPDATE TIPO_DOCUMENTO_PAGO
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_TIPO_DOC = @ID_TIPO_DOC
END
GO

--CRITERIO REBATE
-- OBTENER CRITERIO REBATE
CREATE OR ALTER PROCEDURE SP_OBTENER_CRITERIO_REBATE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        C.ID_CRITERIO,
        C.NOMBRE,
        C.OPERADOR,
        C.DESCRIPCION,
        C.IDESTADO,
        E.NOMBRE AS ESTADO,
        C.FECHA_REGISTRO
    FROM CRITERIO_REBATE C
    INNER JOIN ESTADO E ON C.IDESTADO = E.IDESTADO
END
GO

-- CREAR CRITERIO REBATE
CREATE OR ALTER PROCEDURE SP_CREAR_CRITERIO_REBATE
    @NOMBRE VARCHAR(50),
    @OPERADOR VARCHAR(10),
    @DESCRIPCION VARCHAR(150),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM CRITERIO_REBATE WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('EL CRITERIO YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO CRITERIO_REBATE (NOMBRE, OPERADOR, DESCRIPCION, IDESTADO)
    VALUES (@NOMBRE, @OPERADOR, @DESCRIPCION, @IDESTADO)
END
GO

-- EDITAR CRITERIO REBATE
CREATE OR ALTER PROCEDURE SP_EDITAR_CRITERIO_REBATE
    @ID_CRITERIO INT,
    @NOMBRE VARCHAR(50),
    @OPERADOR VARCHAR(10),
    @DESCRIPCION VARCHAR(150),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM CRITERIO_REBATE WHERE ID_CRITERIO = @ID_CRITERIO)
    BEGIN
        RAISERROR('EL CRITERIO NO EXISTE.',16,1)
        RETURN
    END

    IF EXISTS (SELECT 1 FROM CRITERIO_REBATE WHERE NOMBRE = @NOMBRE AND ID_CRITERIO <> @ID_CRITERIO)
    BEGIN
        RAISERROR('EL NOMBRE DEL CRITERIO YA EXISTE.',16,1)
        RETURN
    END

    UPDATE CRITERIO_REBATE
    SET NOMBRE = @NOMBRE,
        OPERADOR = @OPERADOR,
        DESCRIPCION = @DESCRIPCION,
        IDESTADO = @IDESTADO
    WHERE ID_CRITERIO = @ID_CRITERIO
END
GO


-- OBTENER MODALIDAD OPERACION
CREATE OR ALTER PROCEDURE SP_OBTENER_MODALIDAD_OPERACION
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        M.ID_MODALIDAD_OP,
        M.NOMBRE,
        M.IDESTADO,
        E.NOMBRE AS ESTADO,
        M.FECHA_REGISTRO
    FROM MODALIDAD_OPERACION M
    INNER JOIN ESTADO E ON M.IDESTADO = E.IDESTADO
END
GO

-- CREAR MODALIDAD OPERACION
CREATE OR ALTER PROCEDURE SP_CREAR_MODALIDAD_OPERACION
    @NOMBRE VARCHAR(20),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE NOMBRE = @NOMBRE)
    BEGIN
        RAISERROR('LA MODALIDAD YA EXISTE.',16,1)
        RETURN
    END

    INSERT INTO MODALIDAD_OPERACION (NOMBRE, IDESTADO)
    VALUES (@NOMBRE, @IDESTADO)
END
GO

-- EDITAR MODALIDAD OPERACION
CREATE OR ALTER PROCEDURE SP_EDITAR_MODALIDAD_OPERACION
    @ID_MODALIDAD_OP INT,
    @NOMBRE VARCHAR(20),
    @IDESTADO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE ID_MODALIDAD_OP = @ID_MODALIDAD_OP)
    BEGIN
        RAISERROR('LA MODALIDAD NO EXISTE.',16,1)
        RETURN
    END

    IF EXISTS (SELECT 1 FROM MODALIDAD_OPERACION WHERE NOMBRE = @NOMBRE AND ID_MODALIDAD_OP <> @ID_MODALIDAD_OP)
    BEGIN
        RAISERROR('EL NOMBRE DE LA MODALIDAD YA EXISTE.',16,1)
        RETURN
    END

    UPDATE MODALIDAD_OPERACION
    SET NOMBRE = @NOMBRE,
        IDESTADO = @IDESTADO
    WHERE ID_MODALIDAD_OP = @ID_MODALIDAD_OP
END
GO


----CAMPAÑA PUBLICITARIA 
CREATE OR ALTER PROCEDURE SP_OBTENER_CAMPANIA_PUBLICITARIA
AS
BEGIN
    SELECT 
        C.ID_CAMPANIA,
        C.NUMERO_CAMPANIA,  -- agregado
        C.NOMBRE_CAMPANIA,
        C.MONTO_INVERSION,
        C.FECHA_INICIO,
        C.FECHA_FIN,
        C.FECHA_REGISTRO,

        P.ID_PROVEEDOR,
        P.NOMBRE_PROVEEDOR,

        TP.ID_TIPO_PUBLICIDAD,
        TP.NOMBRE AS TIPO_PUBLICIDAD,

        M.ID_MODALIDAD,
        M.NOMBRE AS MODALIDAD,

        PA.ID_PAIS,
        PA.NOMBRE AS PAIS,

        MO.ID_MONEDA,
        MO.NOMBRE AS MONEDA,

        E.IDESTADO,
        E.NOMBRE AS ESTADO
    FROM CAMPANIA_PUBLICITARIA C
    INNER JOIN PROVEEDORES P ON P.ID_PROVEEDOR = C.ID_PROVEEDOR
    INNER JOIN TIPO_PUBLICIDAD TP ON TP.ID_TIPO_PUBLICIDAD = C.ID_TIPO_PUBLICIDAD
    INNER JOIN MODALIDAD M ON M.ID_MODALIDAD = C.ID_MODALIDAD
    INNER JOIN PAIS PA ON PA.ID_PAIS = C.ID_PAIS
    INNER JOIN MONEDA MO ON MO.ID_MONEDA = C.ID_MONEDA
    INNER JOIN ESTADO E ON E.IDESTADO = C.IDESTADO
    ORDER BY C.FECHA_INICIO ASC; -- Las próximas campañas primero
END
GO


-- Solo se crea una vez
CREATE SEQUENCE SEQ_CODIGO_CAMPANIA
    AS BIGINT
    START WITH 1
    INCREMENT BY 1;
GO


CREATE OR ALTER PROCEDURE SP_CREAR_CAMPANIA_PUBLICITARIA
(
    @NOMBRE_CAMPANIA      VARCHAR(200),
    @ID_PROVEEDOR         INT,
    @ID_TIPO_PUBLICIDAD   INT,
    @ID_MODALIDAD         INT,
    @FECHA_INICIO         DATE,
    @FECHA_FIN            DATE,
    @MONTO_INVERSION      DECIMAL(18,2),
    @ID_PAIS              INT,
    @ID_MONEDA            INT
)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO CAMPANIA_PUBLICITARIA
    (
        NUMERO_CAMPANIA,
        NOMBRE_CAMPANIA,
        ID_PROVEEDOR,
        ID_TIPO_PUBLICIDAD,
        ID_MODALIDAD,
        FECHA_INICIO,
        FECHA_FIN,
        MONTO_INVERSION,
        ID_PAIS,
        ID_MONEDA,
        IDESTADO,
        FECHA_REGISTRO
    )
    VALUES
    (
        'CAM-' + FORMAT(NEXT VALUE FOR SEQ_NUMERO_CAMPANIA, '000000'),
        @NOMBRE_CAMPANIA,
        @ID_PROVEEDOR,
        @ID_TIPO_PUBLICIDAD,
        @ID_MODALIDAD,
        @FECHA_INICIO,
        @FECHA_FIN,
        @MONTO_INVERSION,
        @ID_PAIS,
        @ID_MONEDA,
        DEFAULT,
        GETDATE()
    );
END
GO


CREATE OR ALTER PROCEDURE SP_EDITAR_CAMPANIA_PUBLICITARIA
(
    @ID_CAMPANIA         INT,
    @NOMBRE_CAMPANIA     VARCHAR(200),
    @ID_PROVEEDOR        INT,
    @ID_TIPO_PUBLICIDAD  INT,
    @ID_MODALIDAD        INT,
    @FECHA_INICIO        DATE,
    @FECHA_FIN           DATE,
    @MONTO_INVERSION     DECIMAL(18,2),
    @ID_PAIS             INT,
    @ID_MONEDA           INT
)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE CAMPANIA_PUBLICITARIA
    SET
        NOMBRE_CAMPANIA    = @NOMBRE_CAMPANIA,
        ID_PROVEEDOR       = @ID_PROVEEDOR,
        ID_TIPO_PUBLICIDAD = @ID_TIPO_PUBLICIDAD,
        ID_MODALIDAD       = @ID_MODALIDAD,
        FECHA_INICIO       = @FECHA_INICIO,
        FECHA_FIN          = @FECHA_FIN,
        MONTO_INVERSION    = @MONTO_INVERSION,
        ID_PAIS            = @ID_PAIS,
        ID_MONEDA          = @ID_MONEDA
    WHERE ID_CAMPANIA = @ID_CAMPANIA;
END
GO


---ESTADO PUBLICIDAD CORRECTO 
CREATE OR ALTER PROCEDURE SP_OBTENER_ESTADO_CUENTA_PUBLICIDAD
    @ID_CAMPANIA INT = NULL  -- parámetro opcional, si es NULL trae todas las campañas
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        EC.ID_ESTADO_CUENTA,
        EC.ID_CAMPANIA,
        C.NUMERO_CAMPANIA,       -- Código de campaña
        C.NOMBRE_CAMPANIA,       -- Nombre de campaña
        P.NOMBRE_PROVEEDOR,
        EC.NUMERO_CUOTA,
        EC.FECHA_PAGO_PROGRAMADA,
        EC.MONTO_CUOTA,
        E.NOMBRE AS ESTADO,
        EC.FECHA_REGISTRO
    FROM ESTADO_CUENTA_PUBLICIDAD EC
    INNER JOIN CAMPANIA_PUBLICITARIA C 
        ON C.ID_CAMPANIA = EC.ID_CAMPANIA
    INNER JOIN PROVEEDORES P 
        ON P.ID_PROVEEDOR = C.ID_PROVEEDOR
    INNER JOIN ESTADO E 
        ON E.IDESTADO = EC.IDESTADO
    WHERE EC.IDESTADO = 5  -- Pendiente
      AND (@ID_CAMPANIA IS NULL OR EC.ID_CAMPANIA = @ID_CAMPANIA)
    ORDER BY EC.FECHA_PAGO_PROGRAMADA;
END
GO


--para pagos
-- SP para registrar pago y detalle

CREATE TYPE T_DETALLE_PAGO_PUBLICIDAD AS TABLE
(
    ID_ESTADO_CUENTA INT,
    MONTO_PAGADO DECIMAL(18,2),
    ID_TIPO_DOCUMENTO INT,
    COMPROBANTE VARCHAR(max) -- solo ruta/nombre del archivo
);
GO


CREATE OR ALTER PROCEDURE SP_REGISTRAR_PAGO_PUBLICIDAD
(
    @ID_CAMPANIA INT,
    @FECHA_DOCUMENTO DATE,
    @MONTO_TOTAL DECIMAL(18,2),
    @OBSERVACION VARCHAR(300),
    @DETALLE T_DETALLE_PAGO_PUBLICIDAD READONLY,
    @ID_PAGO INT OUTPUT,
    @NUMERO_DOCUMENTO_OUT VARCHAR(20) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE 
        @CORRELATIVO INT,
        @LARGO INT;

    BEGIN TRY
        BEGIN TRAN;

        -- Obtener el siguiente número de documento
        SELECT @CORRELATIVO = ISNULL(MAX(CAST(NUMERO_DOCUMENTO AS INT)), 0) + 1
        FROM PAGO_PUBLICIDAD;

        -- Mínimo 4 dígitos
        SET @LARGO = CASE WHEN LEN(@CORRELATIVO) < 4 THEN 4 ELSE LEN(@CORRELATIVO) END;

        -- Formatear con ceros a la izquierda
        SET @NUMERO_DOCUMENTO_OUT = RIGHT(REPLICATE('0', @LARGO) + CAST(@CORRELATIVO AS VARCHAR), @LARGO);

        -- Insertar pago principal
        INSERT INTO PAGO_PUBLICIDAD
        (
            ID_CAMPANIA,
            NUMERO_DOCUMENTO,
            FECHA_DOCUMENTO,
            MONTO_TOTAL,
            OBSERVACION,
            IDESTADO,
            FECHA_REGISTRO
        )
        VALUES
        (
            @ID_CAMPANIA,
            @NUMERO_DOCUMENTO_OUT,
            @FECHA_DOCUMENTO,
            @MONTO_TOTAL,
            @OBSERVACION,
            6,
            GETDATE()
        );

        SET @ID_PAGO = SCOPE_IDENTITY();

        -- Insertar los pagos tal como vienen en @DETALLE
        INSERT INTO DETALLE_PAGO_PUBLICIDAD
        (
            ID_PAGO,
            ID_ESTADO_CUENTA,
            MONTO_PAGADO,
            ID_TIPO_DOC,
            COMPROBANTE
        )
        SELECT
            @ID_PAGO,
            ID_ESTADO_CUENTA,
            MONTO_PAGADO,
            ID_TIPO_DOCUMENTO,
            COMPROBANTE
        FROM @DETALLE;

        COMMIT;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        THROW;
    END CATCH
END;


CREATE OR ALTER PROCEDURE SP_LISTA_CAMPANIAS_PUBLICIDAD
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        C.ID_CAMPANIA,
        C.NUMERO_CAMPANIA,
        C.NOMBRE_CAMPANIA,

        P.NOMBRE_PROVEEDOR,
        TP.NOMBRE AS TIPO_PUBLICIDAD,
        M.NOMBRE AS MODALIDAD,
        PA.NOMBRE AS PAIS,
        MO.NOMBRE AS MONEDA,

        C.MONTO_INVERSION,

        ISNULL(SUM(PP.MONTO_TOTAL), 0) AS MONTO_PAGADO,
        C.MONTO_INVERSION - ISNULL(SUM(PP.MONTO_TOTAL), 0) AS SALDO_PENDIENTE,

        EC.NOMBRE AS ESTADO_CAMPANIA,

        C.IDESTADO_PAGO AS ID_ESTADO_PAGO,   -- 🔥 CLAVE
        EP.NOMBRE AS ESTADO_PAGO,

        C.FECHA_INICIO,
        C.FECHA_FIN
    FROM CAMPANIA_PUBLICITARIA C
        INNER JOIN PROVEEDORES P ON P.ID_PROVEEDOR = C.ID_PROVEEDOR
        INNER JOIN TIPO_PUBLICIDAD TP ON TP.ID_TIPO_PUBLICIDAD = C.ID_TIPO_PUBLICIDAD
        INNER JOIN MODALIDAD M ON M.ID_MODALIDAD = C.ID_MODALIDAD
        INNER JOIN PAIS PA ON PA.ID_PAIS = C.ID_PAIS
        INNER JOIN MONEDA MO ON MO.ID_MONEDA = C.ID_MONEDA
        INNER JOIN ESTADO EC ON EC.IDESTADO = C.IDESTADO
        LEFT JOIN ESTADO EP ON EP.IDESTADO = C.IDESTADO_PAGO
        LEFT JOIN PAGO_PUBLICIDAD PP ON PP.ID_CAMPANIA = C.ID_CAMPANIA
    GROUP BY
        C.ID_CAMPANIA,
        C.NUMERO_CAMPANIA,
        C.NOMBRE_CAMPANIA,
        P.NOMBRE_PROVEEDOR,
        TP.NOMBRE,
        M.NOMBRE,
        PA.NOMBRE,
        MO.NOMBRE,
        C.MONTO_INVERSION,
        EC.NOMBRE,
        C.IDESTADO_PAGO,        -- 🔥 OBLIGATORIO
        EP.NOMBRE,
        C.FECHA_INICIO,
        C.FECHA_FIN
    ORDER BY C.FECHA_INICIO ASC;
END
GO


CREATE OR ALTER PROCEDURE SP_DETALLE_PAGO_CAMPANIA
    @ID_CAMPANIA INT
AS
BEGIN
    SELECT 
        DP.ID_DETALLE_PAGO AS IdDetallePago,
        PP.NUMERO_DOCUMENTO AS DocumentoPago,
        DP.MONTO_PAGADO AS MontoPagado,
        TD.NOMBRE AS TipoDocumento,
        PP.FECHA_DOCUMENTO AS FechaDocumento,
        DP.FECHA_REGISTRO AS FechaRegistro,
        DP.COMPROBANTE AS Comprobante
    FROM DETALLE_PAGO_PUBLICIDAD DP
    INNER JOIN PAGO_PUBLICIDAD PP ON PP.ID_PAGO = DP.ID_PAGO
    LEFT JOIN TIPO_DOCUMENTO_PAGO TD ON TD.ID_TIPO_DOC = DP.ID_TIPO_DOC
    WHERE PP.ID_CAMPANIA = @ID_CAMPANIA
    ORDER BY DP.FECHA_REGISTRO ASC;
END
