

CREATE TABLE PAIS (
    ID_PAIS INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_PAIS_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

CREATE TABLE MONEDA (
    ID_MONEDA INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50),
    SIMBOLO VARCHAR(10),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_MONEDA_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO


CREATE TABLE MODALIDAD (
    ID_MODALIDAD INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_MODALIDAD_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO


ALTER TABLE MODALIDAD
ADD 
    TIPO_INTERVALO VARCHAR(10) NULL,
    VALOR_INTERVALO INT NULL;
GO

select * from MODALIDAD

CREATE TABLE TIPO_PUBLICIDAD (
    ID_TIPO_PUBLICIDAD INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TIPO_PUBLICIDAD_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

CREATE TABLE TIPO_REBATE (
    ID_TIPO_REBATE INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(100),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TIPO_REBATE_ESTADO FOREIGN KEY (IDESTADO)
        REFERENCES ESTADO(IDESTADO)
);
GO

CREATE TABLE TIPO_DOCUMENTO_PAGO (
    ID_TIPO_DOC INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TIPO_DOC_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO



--PUBLICIDAD
CREATE TABLE CAMPANIA_PUBLICITARIA (
    ID_CAMPANIA INT IDENTITY PRIMARY KEY,
    NOMBRE_CAMPANIA VARCHAR(200),
    ID_PROVEEDOR INT,
    ID_TIPO_PUBLICIDAD INT,
    ID_MODALIDAD INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    MONTO_INVERSION DECIMAL(18,2),
    ID_PAIS INT,
    ID_MONEDA INT,
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_PROVEEDOR) REFERENCES	PROVEEDORES(ID_PROVEEDOR),
    FOREIGN KEY (ID_TIPO_PUBLICIDAD) REFERENCES TIPO_PUBLICIDAD(ID_TIPO_PUBLICIDAD),
    FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD(ID_MODALIDAD),
    FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID_MONEDA),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

ALTER TABLE CAMPANIA_PUBLICITARIA
ADD NUMERO_CAMPANIA VARCHAR(20) NULL;
GO

CREATE UNIQUE INDEX UX_CAMPANIA_CODIGO
ON CAMPANIA_PUBLICITARIA (NUMERO_CAMPANIA);
GO

ALTER TABLE CAMPANIA_PUBLICITARIA
ADD IDESTADO_PAGO INT NOT NULL DEFAULT 5; -- 5 = PENDIENTE
GO

ALTER TABLE CAMPANIA_PUBLICITARIA
ADD CONSTRAINT FK_CAMPANIA_ESTADO_PAGO
FOREIGN KEY (IDESTADO_PAGO) REFERENCES ESTADO(IDESTADO);
GO


UPDATE CAMPANIA_PUBLICITARIA
SET NUMERO_CAMPANIA = 'CAM-' + RIGHT('000000' + CAST(ID_CAMPANIA AS VARCHAR), 6)
WHERE NUMERO_CAMPANIA IS NULL;
GO


select * from CAMPANIA_PUBLICITARIA

--PARA CUANODE SE CRE UNA NUEVA SSE PONGO EL ESTADO 
ALTER TABLE CAMPANIA_PUBLICITARIA
ADD CONSTRAINT DF_CAMPANIA_ESTADO
DEFAULT 3 FOR IDESTADO; --ESTADO 3 CREADO
GO

CREATE TABLE ESTADO_CUENTA_PUBLICIDAD (
    ID_ESTADO_CUENTA INT IDENTITY PRIMARY KEY,
    ID_CAMPANIA INT NOT NULL,
    NUMERO_CUOTA INT,
    FECHA_PAGO_PROGRAMADA DATE,
    MONTO_CUOTA DECIMAL(18,2),
    IDESTADO INT NOT NULL,       -- Pendiente / Parcial / Pagado
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIA_PUBLICITARIA(ID_CAMPANIA),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);

---correcto eliminar los que estan arriba
CREATE TABLE PAGO_PUBLICIDAD (
    ID_PAGO INT IDENTITY PRIMARY KEY,
    ID_CAMPANIA INT NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(50) NOT NULL,
    FECHA_DOCUMENTO DATE,
    MONTO_TOTAL DECIMAL(18,2),
    OBSERVACION VARCHAR(300),
    IDESTADO INT NOT NULL, 
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIA_PUBLICITARIA(ID_CAMPANIA),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

ALTER TABLE PAGO_PUBLICIDAD
ADD CONSTRAINT UQ_NUMERO_DOCUMENTO UNIQUE(NUMERO_DOCUMENTO);
GO

CREATE TABLE DETALLE_PAGO_PUBLICIDAD (
    ID_DETALLE_PAGO INT IDENTITY PRIMARY KEY,
    ID_PAGO INT NOT NULL,
    ID_ESTADO_CUENTA INT NOT NULL,
    MONTO_PAGADO DECIMAL(18,2) NOT NULL,
    ID_TIPO_DOC INT NOT NULL,
    COMPROBANTE VARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_PAGO) REFERENCES PAGO_PUBLICIDAD(ID_PAGO),
    FOREIGN KEY (ID_ESTADO_CUENTA) REFERENCES ESTADO_CUENTA_PUBLICIDAD(ID_ESTADO_CUENTA),
    FOREIGN KEY (ID_TIPO_DOC) REFERENCES TIPO_DOCUMENTO_PAGO(ID_TIPO_DOC)
);
GO

ALTER TABLE DETALLE_PAGO_PUBLICIDAD
ADD COMPROBANTE VARCHAR(max);  -- o la longitud que consideres suficiente


select * from MODALIDAD


CREATE TABLE MODALIDAD_OPERACION (
    ID_MODALIDAD_OP INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(20), -- COMPRA / VENTA
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
GO



CREATE TABLE CRITERIO_REBATE (
    ID_CRITERIO INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50),       -- Mayor que, Incremento, Porcentaje
    OPERADOR VARCHAR(10),    -- >, >=, +, %
    DESCRIPCION VARCHAR(150),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

select* from CRITERIO_REBATE

--REBATE
-- Crear la secuencia para el número de documento
CREATE SEQUENCE SEQ_NUMERO_ACUERDO
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE ACUERDO_REBATE (
    ID_ACUERDO INT IDENTITY PRIMARY KEY,
	NOMBRE_ACUERDO VARCHAR(200),
    NUMERO_ACUERDO VARCHAR(20) NOT NULL,   -- Número de acuerdo automático
    ID_PROVEEDOR INT NOT NULL,
    ID_MODALIDAD_OP INT NOT NULL,          -- COMPRA / VENTA
    ID_TIPO_REBATE INT NOT NULL,           -- Volumen / Crecimiento / Metas
    ID_CRITERIO INT NOT NULL,              -- Mayor que, %, Incremento
    VALOR_CRITERIO DECIMAL(18,2),
    ID_PAIS INT NOT NULL,                  -- Nuevo campo país
    ID_MONEDA INT NOT NULL,                -- Nuevo campo moneda
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	COMENTARIO VARCHAR(MAX),

    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR),
    FOREIGN KEY (ID_MODALIDAD_OP) REFERENCES MODALIDAD_OPERACION(ID_MODALIDAD_OP),
    FOREIGN KEY (ID_TIPO_REBATE) REFERENCES TIPO_REBATE(ID_TIPO_REBATE),
    FOREIGN KEY (ID_CRITERIO) REFERENCES CRITERIO_REBATE(ID_CRITERIO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),           -- FK a tabla PAIS
    FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID_MONEDA),     -- FK a tabla MONEDA
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

ALTER TABLE ACUERDO_REBATE
ADD GANANCIA DECIMAL(18,2);  -- Este es el monto que se pagará si cumple

UPDATE ACUERDO_REBATE
SET GANANCIA = 1500
WHERE ID_ACUERDO = 2;  -- Aquí pones el ID del acuerdo que quieres actualizar

select * from ACUERDO_REBATE
ALTER TABLE ACUERDO_REBATE
ADD CONSTRAINT DF_REBATE_ESTADO
DEFAULT 3 FOR IDESTADO; --ESTADO 3 CREADO
GO

CREATE TABLE EJECUCION_REBATE (
    ID_EJECUCION INT IDENTITY PRIMARY KEY,
    ID_ACUERDO INT,
    NUMERO_DOCUMENTO_SOPORTE VARCHAR(100),
    MONTO_CALCULADO DECIMAL(18,2),
    CUMPLE_CONDICION BIT,
    ARCHIVO_SOPORTE VARCHAR(300),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_ACUERDO) REFERENCES ACUERDO_REBATE(ID_ACUERDO),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

select * from Estado
ALTER TABLE EJECUCION_REBATE
ADD MONTO_REBATE DECIMAL(18,2) NULL;



CREATE TABLE PAGO_REBATE (
    ID_PAGO_REBATE INT IDENTITY PRIMARY KEY,
    ID_ACUERDO INT NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(50) NOT NULL,
    MONTO_TOTAL DECIMAL(18,2) NOT NULL,
    OBSERVACION VARCHAR(300),
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_ACUERDO) REFERENCES ACUERDO_REBATE(ID_ACUERDO),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

ALTER TABLE PAGO_REBATE
ADD CONSTRAINT UQ_PAGO_REBATE_NUMERO UNIQUE (NUMERO_DOCUMENTO);
GO

CREATE TABLE DETALLE_PAGO_REBATE (
    ID_DETALLE_PAGO INT IDENTITY PRIMARY KEY,
    ID_PAGO_REBATE INT NOT NULL,
    ID_EJECUCION INT NOT NULL,
    MONTO_PAGADO DECIMAL(18,2) NOT NULL,
    ID_TIPO_DOC INT NOT NULL,
    COMPROBANTE VARCHAR(MAX),
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_PAGO_REBATE) REFERENCES PAGO_REBATE(ID_PAGO_REBATE),
    FOREIGN KEY (ID_EJECUCION) REFERENCES EJECUCION_REBATE(ID_EJECUCION),
    FOREIGN KEY (ID_TIPO_DOC) REFERENCES TIPO_DOCUMENTO_PAGO(ID_TIPO_DOC)
);
GO

--NOTA DE CREDITO
CREATE TABLE NOTA_CREDITO (
    ID_NC INT IDENTITY(1,1) PRIMARY KEY,

    -- PROVEEDOR
    ID_PROVEEDOR INT NOT NULL,

    -- DATOS DEL DOCUMENTO
    NUMERO_NC VARCHAR(50) NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,

    -- ESTADO (ACTIVA, APLICADA, ANULADA)
    IDESTADO INT NOT NULL,

    DOCUMENTO_ADJUNTO VARCHAR(300),

    -- ORIGEN DEL DINERO
    TIPO_ORIGEN VARCHAR(20) NOT NULL, 
    -- 'PUBLICIDAD' | 'REBATE' | 'VENCIDO'

    ID_ORIGEN INT NOT NULL,
    -- ID_CAMPANIA / ID_EJECUCION_REBATE / ID_ESTADO_CUENTA

    NUMERO_DOCUMENTO_ORIGEN VARCHAR(50), -- <--- NUEVA COLUMNA

    FECHA_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_NC_PROVEEDOR
        FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),

    CONSTRAINT FK_NC_ESTADO
        FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO


--- PENDIENTE DE CREAR 

CREATE TABLE APLICACION_NOTA_CREDITO (
    ID_APLICACION INT IDENTITY PRIMARY KEY,
    ID_NC INT NOT NULL,
    ID_FACTURA INT NOT NULL,
    MONTO_APLICADO DECIMAL(18,2) NOT NULL,
    FECHA_APLICACION DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_NC) REFERENCES NOTA_CREDITO(ID_NC),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);




--CUENTAS POR COBRAR 
CREATE TABLE CUENTA_POR_COBRAR (
    ID_CUENTA INT IDENTITY PRIMARY KEY,
    ID_PROVEEDOR INT,
    TIPO_ORIGEN VARCHAR(30),
    ID_ORIGEN INT,
    MONTO_ORIGINAL DECIMAL(18,2),
    MONTO_PAGADO DECIMAL(18,2),
    SALDO DECIMAL(18,2),
    FECHA_VENCIMIENTO DATE,
    DIAS_MORA INT,
    IDESTADO INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);
GO

select * from CAMPANIA_PUBLICITARIA
select * from PAGO_PUBLICIDAD
select * from DETALLE_PAGO_PUBLICIDAD


